<?php
die("<!DOCTYPE html><html><body><h1>GSys Internetional Structure</h1><sup style=\"position: fixed; bottom:1em; right:1em\">&copy;GHvernuft.nl</sup></body></html>");

$redir = __DIR__."/./os/haiku.html";
$redir = __DIR__."/./Sys/Frame/test.php";
echo "\n<br/>".__FILE__.__LINE__." docroot ".$_SERVER['DOCUMENT_ROOT'];
$redir = $_SERVER['DOCUMENT_ROOT']."/Sys/Frame/test.php";
echo "\n<br/>".__FILE__.__LINE__." redir ". $redir;
require $redir;
die("Generated by Internetional Framework");